//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeChallenge.Application.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CodeChallenge.Application.Resources.ErrorResource", typeof(ErrorResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ویزیتی با این کد وجود ندارد.
        /// </summary>
        internal static string AppointmentDoesNotExist {
            get {
                return ResourceManager.GetString("AppointmentDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برای این دکتر یا بیمار نوبت ویزیت وجود دارد.
        /// </summary>
        internal static string AppointmentExist {
            get {
                return ResourceManager.GetString("AppointmentExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رکورد شما به دلیل مشکلاتی ایجاد نشد.
        /// </summary>
        internal static string CreateNotSuccess {
            get {
                return ResourceManager.GetString("CreateNotSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رکورد شما با موفقیت ایجاد شد.
        /// </summary>
        internal static string CreateSuccess {
            get {
                return ResourceManager.GetString("CreateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ شروع باید از تاریخ پایان کوچکتر باشد .
        /// </summary>
        internal static string DateCheck {
            get {
                return ResourceManager.GetString("DateCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف اطلاعات به دلیل مشکلاتی با موفقیت انجام نشد.
        /// </summary>
        internal static string DeleteNotSuccess {
            get {
                return ResourceManager.GetString("DeleteNotSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رکورد شما با موفقیت حذف شد.
        /// </summary>
        internal static string DeleteSuccess {
            get {
                return ResourceManager.GetString("DeleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دکتر انتخاب شده وجود ندارد.
        /// </summary>
        internal static string DoctorNotExist {
            get {
                return ResourceManager.GetString("DoctorNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زمانی برای رزو ویزیت وجود ندارد.
        /// </summary>
        internal static string DoesNotExistTimeForAppointment {
            get {
                return ResourceManager.GetString("DoesNotExistTimeForAppointment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to این کد قبلا در سیستم تعریف شده است.
        /// </summary>
        internal static string EarlyExist {
            get {
                return ResourceManager.GetString("EarlyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to این ایمیل قبلا در سیستم ثبت شده است.
        /// </summary>
        internal static string EmailEarlyExist {
            get {
                return ResourceManager.GetString("EmailEarlyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع جنسیت وارد شده صحیح نمی باشد.
        /// </summary>
        internal static string GenderCheck {
            get {
                return ResourceManager.GetString("GenderCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to محدوده حداقل و حداکثر زمان ملاقات  برای دکتر عمومی درست نیست.
        /// </summary>
        internal static string GereralTimeAppointment {
            get {
                return ResourceManager.GetString("GereralTimeAppointment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هر بیمار در روز بیشتر از 2 ویزیت نمی نواند داشته باشد.
        /// </summary>
        internal static string MaxAppoinyInDay {
            get {
                return ResourceManager.GetString("MaxAppoinyInDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to این کد ملی قبلا در سیستم ثبت شده است.
        /// </summary>
        internal static string NationalCodeEarlyExist {
            get {
                return ResourceManager.GetString("NationalCodeEarlyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رکوردی با این مشخصات وجود ندارد.
        /// </summary>
        internal static string NotExist {
            get {
                return ResourceManager.GetString("NotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هیچ یک از پارامترها پر نشده اند.
        /// </summary>
        internal static string NotFillParameters {
            get {
                return ResourceManager.GetString("NotFillParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بیماری با این مشخصات وجود دارد.
        /// </summary>
        internal static string PatientExist {
            get {
                return ResourceManager.GetString("PatientExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برای این بیمار در سیستم وقت ویزیت صادر شده است.
        /// </summary>
        internal static string PatientHasVisit {
            get {
                return ResourceManager.GetString("PatientHasVisit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بیماری با این مشخصات وجود ندارد.
        /// </summary>
        internal static string PatientNotExist {
            get {
                return ResourceManager.GetString("PatientNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ مورد نظر دارای تداخل زمانی است.
        /// </summary>
        internal static string SchedulerConflict {
            get {
                return ResourceManager.GetString("SchedulerConflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برای این دکتر برنامه ی کاری وجود دارد.
        /// </summary>
        internal static string SchedulerExist {
            get {
                return ResourceManager.GetString("SchedulerExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برای این دکتر در این زمان وقت ویزیت صادر شده است.
        /// </summary>
        internal static string SchedulerExistVisit {
            get {
                return ResourceManager.GetString("SchedulerExistVisit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to محدوده حداقل و حداکثر زمان ملاقات  برای دکتر متخصص درست نیست.
        /// </summary>
        internal static string SpecialistTimeAppointment {
            get {
                return ResourceManager.GetString("SpecialistTimeAppointment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع دکتر وارد شده صحیح نمی باشد.
        /// </summary>
        internal static string TypeDoctorCheck {
            get {
                return ResourceManager.GetString("TypeDoctorCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اصلاح اطلاعات به دلیل مشکلاتی با موفقیت انجام نشد.
        /// </summary>
        internal static string UpdateNotSuccess {
            get {
                return ResourceManager.GetString("UpdateNotSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اصلاح اطلاعات با موفقیت انجام شد.
        /// </summary>
        internal static string UpdateSuccess {
            get {
                return ResourceManager.GetString("UpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to روز یا ساعات درخواستی با روز یا ساعات کاری مغایرت دارد.
        /// </summary>
        internal static string ValidationDayOfWeek {
            get {
                return ResourceManager.GetString("ValidationDayOfWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دکتر یا بیمار انتخاب شده اشتباه است.
        /// </summary>
        internal static string ValidationDoctorAndPatient {
            get {
                return ResourceManager.GetString("ValidationDoctorAndPatient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدت زمان انتخاب شده درست نمی باشد.
        /// </summary>
        internal static string ValidationDuration {
            get {
                return ResourceManager.GetString("ValidationDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پارامترهای وارد شده معتبر نیست.
        /// </summary>
        internal static string ValidationError {
            get {
                return ResourceManager.GetString("ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زمان بندی دکتر مربوطه در زمان درخواست شده شما وجود ندارد.
        /// </summary>
        internal static string ValidationSchedul {
            get {
                return ResourceManager.GetString("ValidationSchedul", resourceCulture);
            }
        }
    }
}
